NumPy  practice 

In [1]:
# NumPy is a powerful library for numerical operations in Python.
import numpy as np

In [2]:
# Create a NumPy array 'a' with numbers from 1 to 10.
a = np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
# Create a NumPy array 'b' with numbers from 11 to 20.
b = np.arange(11,21)
print(b)

[11 12 13 14 15 16 17 18 19 20]


In [4]:
# Concatenate arrays 'a' and 'b' into a single array 'ab'.
ab = np.concatenate((a,b))
print(ab)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [5]:
# Calculate the product of all elements in 'ab' and round the result.
ab.prod().round()

np.int64(2432902008176640000)

In [6]:
# Perform a dot product between arrays 'a' and 'b'.
a@b

np.int64(935)

In [7]:
# Access the element at index 10 in the array 'ab'.
ab[10]

np.int64(11)

In [8]:
# Create a new NumPy array 'ba'.
ba = np.array([9,8,7,6,5,4,3,2,6,4,8,3,54,677,867])
# Sort the elements of 'ba' in ascending order.
print(np.sort(ba))

[  2   3   3   4   4   5   6   6   7   8   8   9  54 677 867]


In [9]:
# Create a 3x3 NumPy array 'sm'.
sm = np.array([[1,2,3],
                [6,4,2],
                [0,9,7]])
# Sort the elements of each row (axis=1) of 'sm'.
ma = np.sort(sm, axis=1)
ma1 = np.sort(sm,axis=0)
print(ma)

[[1 2 3]
 [2 4 6]
 [0 7 9]]


In [10]:
ma1

array([[0, 2, 2],
       [1, 4, 3],
       [6, 9, 7]])

In [11]:
# Sort the elements of each column (axis=0) of 'sm'.
ms = np.sort(sm, axis=0)
print(ms)

[[0 2 2]
 [1 4 3]
 [6 9 7]]


In [12]:
# Square each element of the array 'sm'.
x = sm**2
print(x)

[[ 1  4  9]
 [36 16  4]
 [ 0 81 49]]


In [13]:
# Create a new array 'sm' with numbers from 1 to 19.
sm = np.arange(1,20)
print(sm)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [14]:
# Create a list of indices.
indies = [2,3,0]
# Create a new array 'new' by selecting elements from 'sm' at the specified indices.
new = sm[indies]
print(new)

[3 4 1]


In [15]:
# Create another list of indices.
index = [9,14,16]
# Create another new array 'new1' from 'sm' using the new indices.
new1 = sm[index]
print(new1)

[10 15 17]


In [16]:
# Concatenate 'new' and 'new1'.
n = np.concatenate((new,new1))
# Reshape the concatenated array into a 2x3 matrix.
re = n.reshape(2,3)
print(re)

[[ 3  4  1]
 [10 15 17]]



In [17]:
# Transpose the matrix 're'.
re.T

array([[ 3, 10],
       [ 4, 15],
       [ 1, 17]])

In [18]:
# Calculate the product of all elements in 're'.
re.prod()

np.int64(30600)

In [19]:
# Calculate the cumulative sum of the elements in 're'.
re.cumsum()

array([ 3,  7,  8, 18, 33, 50])

In [20]:
# Flatten the matrix 're' into a 1D array.
re.flatten()

array([ 3,  4,  1, 10, 15, 17])

In [21]:
# Print the 're' matrix.
print(re)

[[ 3  4  1]
 [10 15 17]]


In [22]:
# Create a 2x4 NumPy array 'y'.
y = np.array([[1,2,3,4],[5,6,7,8]])
print(y)

[[1 2 3 4]
 [5 6 7 8]]


In [23]:
# Create a 1x4 NumPy array 'z'.
z = np.array([[1,4,6,9]])
print(z)

[[1 4 6 9]]


In [24]:
# Add arrays 'y' and 'z'. This works because of broadcasting.
yz = y+z
print(yz)

[[ 2  6  9 13]
 [ 6 10 13 17]]


In [25]:
f = np.vstack((y,z))
print(f)

[[1 2 3 4]
 [5 6 7 8]
 [1 4 6 9]]



In [26]:
r = np.array([[1,2,3,4],[5,6,7,8]])
p = np.array([[10,20,30,40],[50,60,70,80]])
rp = np.hstack((r,p))
print(rp)
print()
print(np.vstack((r,p)))

[[ 1  2  3  4 10 20 30 40]
 [ 5  6  7  8 50 60 70 80]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [10 20 30 40]
 [50 60 70 80]]


In [27]:
a = np.random.randint(1,11 , size =(2,3,4))


In [28]:
a

array([[[ 7,  8,  9,  6],
        [10,  5,  6,  8],
        [ 4,  4, 10,  6]],

       [[ 5,  2,  5,  3],
        [ 4,  2,  4,  5],
        [ 9,  5, 10,  5]]])

In [29]:
b.ndim

1

In [30]:
b = np.random.randint(11,21,size = (2,3,4))

In [31]:
ab = np.vstack((a,b))

In [32]:
ab

array([[[ 7,  8,  9,  6],
        [10,  5,  6,  8],
        [ 4,  4, 10,  6]],

       [[ 5,  2,  5,  3],
        [ 4,  2,  4,  5],
        [ 9,  5, 10,  5]],

       [[18, 16, 20, 16],
        [19, 19, 16, 16],
        [20, 14, 15, 14]],

       [[18, 11, 15, 17],
        [11, 15, 11, 17],
        [19, 15, 18, 11]]])

In [72]:
ab[3,1]

array([11, 15, 11, 17])

In [71]:
ab[2,0]

array([18, 16, 20, 16])

In [68]:
ab[1,:,2:4]

array([[ 5,  3],
       [ 4,  5],
       [10,  5]])

In [67]:
ab[3,0:2,2:4]

array([[15, 17],
       [11, 17]])

In [33]:
ab[2:4,0:3,0]

array([[18, 19, 20],
       [18, 11, 19]])

In [34]:
ab[:,:,2:4]

array([[[ 9,  6],
        [ 6,  8],
        [10,  6]],

       [[ 5,  3],
        [ 4,  5],
        [10,  5]],

       [[20, 16],
        [16, 16],
        [15, 14]],

       [[15, 17],
        [11, 17],
        [18, 11]]])

In [35]:
ab[0:2,1:3,0:1]

array([[[10],
        [ 4]],

       [[ 4],
        [ 9]]])

In [36]:
ab[2:4,1:3,2:4]

array([[[16, 16],
        [15, 14]],

       [[11, 17],
        [18, 11]]])

In [37]:
ab[1,2,3]

np.int64(5)

In [38]:
ab.cumsum()

array([  7,  15,  24,  30,  40,  45,  51,  59,  63,  67,  77,  83,  88,
        90,  95,  98, 102, 104, 108, 113, 122, 127, 137, 142, 160, 176,
       196, 212, 231, 250, 266, 282, 302, 316, 331, 345, 363, 374, 389,
       406, 417, 432, 443, 460, 479, 494, 512, 523])

In [39]:
bc = np.log(ab)
bc

array([[[1.94591015, 2.07944154, 2.19722458, 1.79175947],
        [2.30258509, 1.60943791, 1.79175947, 2.07944154],
        [1.38629436, 1.38629436, 2.30258509, 1.79175947]],

       [[1.60943791, 0.69314718, 1.60943791, 1.09861229],
        [1.38629436, 0.69314718, 1.38629436, 1.60943791],
        [2.19722458, 1.60943791, 2.30258509, 1.60943791]],

       [[2.89037176, 2.77258872, 2.99573227, 2.77258872],
        [2.94443898, 2.94443898, 2.77258872, 2.77258872],
        [2.99573227, 2.63905733, 2.7080502 , 2.63905733]],

       [[2.89037176, 2.39789527, 2.7080502 , 2.83321334],
        [2.39789527, 2.7080502 , 2.39789527, 2.83321334],
        [2.94443898, 2.7080502 , 2.89037176, 2.39789527]]])

In [40]:
ab[:,:,0]

array([[ 7, 10,  4],
       [ 5,  4,  9],
       [18, 19, 20],
       [18, 11, 19]])

In [41]:
ab[:,:,2]

array([[ 9,  6, 10],
       [ 5,  4, 10],
       [20, 16, 15],
       [15, 11, 18]])

In [42]:
ab.ndim

3

In [43]:
ba = ab.reshape(4,4,3)

In [44]:
ba

array([[[ 7,  8,  9],
        [ 6, 10,  5],
        [ 6,  8,  4],
        [ 4, 10,  6]],

       [[ 5,  2,  5],
        [ 3,  4,  2],
        [ 4,  5,  9],
        [ 5, 10,  5]],

       [[18, 16, 20],
        [16, 19, 19],
        [16, 16, 20],
        [14, 15, 14]],

       [[18, 11, 15],
        [17, 11, 15],
        [11, 17, 19],
        [15, 18, 11]]])

In [45]:
ba[1,3,1]

np.int64(10)

In [46]:
sm = ba[:,:,2]
sm

array([[ 9,  5,  4,  6],
       [ 5,  2,  9,  5],
       [20, 19, 20, 14],
       [15, 15, 19, 11]])

In [47]:
sm1 = ba[:,:,0]
sm1

array([[ 7,  6,  6,  4],
       [ 5,  3,  4,  5],
       [18, 16, 16, 14],
       [18, 17, 11, 15]])

In [48]:
new2 = np.vstack((sm,sm1))
new2

array([[ 9,  5,  4,  6],
       [ 5,  2,  9,  5],
       [20, 19, 20, 14],
       [15, 15, 19, 11],
       [ 7,  6,  6,  4],
       [ 5,  3,  4,  5],
       [18, 16, 16, 14],
       [18, 17, 11, 15]])

In [49]:
new2.cumsum()

array([  9,  14,  18,  24,  29,  31,  40,  45,  65,  84, 104, 118, 133,
       148, 167, 178, 185, 191, 197, 201, 206, 209, 213, 218, 236, 252,
       268, 282, 300, 317, 328, 343])

In [50]:
new2[7,2]

np.int64(11)

In [51]:
vs = new2.reshape(2,4,4)
vs

array([[[ 9,  5,  4,  6],
        [ 5,  2,  9,  5],
        [20, 19, 20, 14],
        [15, 15, 19, 11]],

       [[ 7,  6,  6,  4],
        [ 5,  3,  4,  5],
        [18, 16, 16, 14],
        [18, 17, 11, 15]]])

In [52]:
vs.shape

(2, 4, 4)

In [53]:
vs.ndim

3

In [54]:
d = np.random.randint(1,11,size=(4,4))
d

array([[ 6,  9,  4,  7],
       [ 9,  3,  6, 10],
       [ 3,  8,  5,  3],
       [ 2,  9,  2,  6]])

In [55]:
vs

array([[[ 9,  5,  4,  6],
        [ 5,  2,  9,  5],
        [20, 19, 20, 14],
        [15, 15, 19, 11]],

       [[ 7,  6,  6,  4],
        [ 5,  3,  4,  5],
        [18, 16, 16, 14],
        [18, 17, 11, 15]]])

In [56]:
brod = vs + d
brod

array([[[15, 14,  8, 13],
        [14,  5, 15, 15],
        [23, 27, 25, 17],
        [17, 24, 21, 17]],

       [[13, 15, 10, 11],
        [14,  6, 10, 15],
        [21, 24, 21, 17],
        [20, 26, 13, 21]]])

In [57]:
mask = brod > 10
# brod.sum(mask)
total = brod[mask].sum()
total

np.int64(488)

In [58]:
brod.sum()

np.int64(527)

In [59]:
xy = np.where(vs == 10,'sachin_veena',vs)
xy

array([[['9', '5', '4', '6'],
        ['5', '2', '9', '5'],
        ['20', '19', '20', '14'],
        ['15', '15', '19', '11']],

       [['7', '6', '6', '4'],
        ['5', '3', '4', '5'],
        ['18', '16', '16', '14'],
        ['18', '17', '11', '15']]], dtype='<U21')